### PR TITLE
workload: use kubeconfig key of KubernetesCluster connection secret f…

### PR DESCRIPTION
**Pull request by muvaf**
### Description of your changes

`kubeconfig` key is common to all `KuberentesCluster` connection secrets and it saves us from doing the parsing and client construction.

Fixes https://github.com/crossplaneio/crossplane/issues/1108

### Checklist

I have:
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Ensured this PR contains a neat, self documenting set of commits.
- [x] Updated any relevant [documentation] and [examples].
- [x] Reported all new error conditions into the log or as an event, as
  appropriate.

For more about what we believe makes a pull request complete, see our
[definition of done].

[documentation]: https://github.com/crossplaneio/crossplane/tree/master/docs
[examples]: https://github.com/crossplaneio/crossplane/tree/master/cluster/examples
[definition of done]: https://github.com/crossplaneio/crossplane/tree/master/design/one-pager-definition-of-done.md

### CODE REVIEW

**Comment by muvaf** [comment]
Manually validated this PR with Wordpress sample stack & GCP.

**Comment by muvaf** [comment]
@hasheddan that makes sense, just updated the PR.

**Comment by negz** [comment]
I'm going to echo @hasheddan's sentiment in that it would be good to confirm that we've tested this and it works, but given how small the change is I'm going to optimistically merge it in the meantime.

**Comment by muvaf** [comment]
> Manually validated this PR with Wordpress sample stack & GCP.

@negz I've tested the case where it uses only `kubeconfig` key without a fallback. In its final form, it has a fallback, which is the old logic, in case that key doesn't have any value. So, IMO it should be fine but I'll do some tests for other things today and I'd use the latest master to test this as well, just in case.

**Pull request merged**
