### PR TITLE
copyright: bump from 2019 to 2020

### PR DESCRIPTION
**Pull request by hasheddan**
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>

### Description of your changes

Someone had to do it  :smile: . Happy New Year Crossplane!

### How has this code been tested?

N/a

### Checklist

I have:
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Ensured this PR contains a neat, self documenting set of commits.
- [x] Updated any relevant [documentation] and [examples].
- [x] Reported all new error conditions into the log or as an event, as
  appropriate.

For more about what we believe makes a pull request complete, see our
[definition of done].

[documentation]: https://github.com/crossplaneio/crossplane/tree/master/docs
[examples]: https://github.com/crossplaneio/crossplane/tree/master/cluster/examples
[definition of done]: https://github.com/crossplaneio/crossplane/tree/master/design/one-pager-definition-of-done.md

### CODE REVIEW

**Comment by hasheddan** [comment]
@jbw976 To be honest, I am not sure, but I definitely do not think it *has* to be updated (many other projects do not update their copyright and everything I have read says that it is not required). In fact, the header appears to not even be *required* as it is just a Copyright notice. I was mostly acting on the memory of this PR https://github.com/crossplaneio/crossplane/pull/570. Definitely feel free to close this (and corresponding stacks PR's) if you feel good about keeping it as is :) it may be best to keep it as is to not set this update as a maintenance expectation in future years.

**Comment by negz** [comment]
https://github.com/crossplaneio/crossplane/pull/570#issuecomment-510312068

This comment might provide some context on the previous bump. I tend to agree with @jbw976 that we shouldn't be bumping copyright years in general - it seems like I did it last time as a bit of a hack to make it easier to appease Sonarcloud, which is not a system I'm personally a big fan of in the first place.

**Comment by hasheddan** [comment]
@negz sounds good to me, shall I close this and related issues?

**Comment by negz** [comment]
@hasheddan Yes please - I think the logic of leaving the copyright at the time the work is first authored makes sense.

**Pull request closed without merging**
