### PR TITLE
Adding logging helpers that uses logr interface with zapr implementation underneath

### LINKED ISSUE #7: Controllers should use consistent logging
We should decide on a single logging package and be consistent with it.  The logging package should support:
* concurrent usage
* configurable levels
* log file rollover

`log.Printf` is not sufficient for these goals.

### PR DESCRIPTION
**Pull request by venuchitta**
**Description of your changes:**
Adding `pkg/log` package which has logging related files. We decided to use `logr` as base interface for crossplane's logging system after going through https://dave.cheney.net/2015/11/05/lets-talk-about-logging and https://github.com/go-logr/logr/blob/master/README.md. 
[zapr](https://github.com/go-logr/zapr) is [logr](https://github.com/go-logr/logr) 's implementation of zap.
`pkg/log/zap/zap.go` uses Uber's [zap](https://github.com/uber-go/zap) with `zapr` implementation of `logr` interface.

**Which issue is resolved by this Pull Request:**
Resolves #7 

**Checklist:**
- [ ] Documentation has been updated, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make generate`) has been run to update object specifications, if necessary.
- [ ] CRD manifests generation (`make manifests`) has been run to update CRD manifests yaml file specifications, if necessary.
- [ ] Update dependencies (`make vendor`) has been run to update `Gopkg.lock` file, if necessary
- [ ] All related commits have been squashed to improve readability.
- [ ] Comments have been added or updated based on the standards set in [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md#comments)

### CODE REVIEW

**Comment by ichekrygin** [comment]
@venuchitta - couple of points here:
1. `Crossplane` is using `controller-runtime` as it's operator framework, thus it is "tied" to it for reasons other than logging.
2. `controller-runtime` itself does not define nor implement logging interface. Instead it "depends" on:
- github.com/go-logr/logr : "A more minimal logging API for Go" (i.e. interface)
- https://github.com/go-logr/zapr:  "A logr implementation using Zap."
Thus we can either use `controller-runtime/pkg/runtime/log` with transient dependency on the above, or we can take direct dependency on both of `logr` and `zapr`, just for the sake of keeping `controller-runtime/pkg/runtime/log` out of the loop. Either case, IMHO, would be more preferable to adding `zap` logger  directly to `Crossplane`. 

I lean towards the former, i.e. using `controller-runtime/pkg/runtime/log` option.

**Comment by negz** [comment]
Hi @venuchitta, just checking in to see if you're still interested on working on this issue?

I tend to agree with @ichekrygin that simply using the logger provided by the controller-runtime makes the most sense (though I'm not entirely sure whether we're supposed to use `controller-runtime/pkg/runtime/log` or `controller-runtime/pkg/log`?). I understand that our proposed approach makes the work a little less interesting, so I'd be happy to take the issue if you'd prefer to tackle something more engaging.

**Comment by venuchitta** [comment]
Hey @negz, I just was occupied with some work. I should be addressing review comments in next couple days.

**Comment by negz** [comment]
That's great news! Sounds good.

**Comment by negz** [comment]
Per #7 @venuchitta mentioned he's been swamped at work and isn't likely to get around to this soon. I've raised #354 with my own take on how we might handle logging.

**Comment by negz** [comment]
Thanks for taking a pass at this @venuchitta, we really appreciate it! We ended up merging similar functionality in https://github.com/crossplaneio/crossplane/pull/354.

**Pull request closed without merging**
