### PR TITLE
Add mapRoles, and mapUsers support on EKS

### LINKED ISSUE #200: EKS Add mapUsers and mapRoles configuration in EKSClusterSpec
EKS clusters have a configurable auth system in place for configuring the mapping of amazon users to kubernetes groups, and for configuring the mapping of amazon roles to kubernetes groups. 

This can be used to add a single user to a cluster, or to integrate more complicated concepts of aws auth into the cluster.

Source documentation of feature: 

Adding users access to the cluster:
https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html

Full choice of auth configuration options at bottom of readme:
https://github.com/kubernetes-sigs/aws-iam-authenticator/blob/master/README.md

### PR DESCRIPTION
**Pull request by lukeweber**
**Description of your changes:**
Adding configuration option for mapUser and mapRoles on EKSClusters. Additional details in ticket. We were programmatically auto generating the default MapRoles required for nodes to join, but have exposed the configuration for additional use cases.

**Which issue is resolved by this Pull Request:**
Resolves #200

### CODE REVIEW

**Comment by lukeweber** [comment]
I'm reticent to add detailed docs as it's mostly an internal component of EKS iam behavior, which I documented in #200 

If you would still like to add this documentation given these comments, please let me know your thoughts of where to add.

**Comment by ichekrygin** [comment]
@lukeweber to clarify the Spec fields: `mapUsers` and `mapFields` are intended for internal processing, i.e. not intended to be specified by "user"?

**Comment by lukeweber** [comment]
For advanced configuration they would be specified in exactly the same format as described here: https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html

With additional configuration options described here: https://github.com/kubernetes-sigs/aws-iam-authenticator/blob/master/README.md

**Comment by ichekrygin** [comment]
Per discussion w/ @lukeweber , example of user/roles mapping:
```yaml
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::555555555555:role/devel-worker-nodes-NodeInstanceRole-74RF4UBDUKL6
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::555555555555:user/admin
      username: admin
      groups:
        - system:masters
    - userarn: arn:aws:iam::111122223333:user/ops-user
      username: ops-user
      groups:
        - system:masters
```
and 
```yaml
  # each mapRoles entry maps an IAM role to a username and set of groups
  # Each username and group can optionally contain template parameters:
  #  1) "{{AccountID}}" is the 12 digit AWS ID.
  #  2) "{{SessionName}}" is the role session name.
  mapRoles:
  # statically map arn:aws:iam::000000000000:role/KubernetesAdmin to cluster admin
  - roleARN: arn:aws:iam::000000000000:role/KubernetesAdmin
    username: kubernetes-admin
    groups:
    - system:masters

  # map EC2 instances in my "KubernetesNode" role to users like
  # "aws:000000000000:instance:i-0123456789abcdef0". Only use this if you
  # trust that the role can only be assumed by EC2 instances. If an IAM user
  # can assume this role directly (with sts:AssumeRole) they can control
  # SessionName.
  - roleARN: arn:aws:iam::000000000000:role/KubernetesNode
    username: aws:{{AccountID}}:instance:{{SessionName}}
    groups:
    - system:bootstrappers
    - aws:instances

  # map nodes that should conform to the username "system:node:<private-DNS>".  This
  # requires the authenticator to query the EC2 API in order to discover the private
  # DNS of the EC2 instance originating the authentication request.  Optionally, you
  # may specify a role that should be assumed before querying the EC2 API with the
  # key "server.ec2DescribeInstancesRoleARN" (see above).
  - roleARN: arn:aws:iam::000000000000:role/KubernetesNode
    username: system:node:{{EC2PrivateDNSName}}
    groups:
    - system:nodes
    - system:bootstrappers

  # map federated users in my "KubernetesAdmin" role to users like
  # "admin:alice-example.com". The SessionName is an arbitrary role name
  # like an e-mail address passed by the identity provider. Note that if this
  # role is assumed directly by an IAM User (not via federation), the user
  # can control the SessionName.
  - roleARN: arn:aws:iam::000000000000:role/KubernetesAdmin
    username: admin:{{SessionName}}
    groups:
    - system:masters

  # each mapUsers entry maps an IAM role to a static username and set of groups
  mapUsers:
  # map user IAM user Alice in 000000000000 to user "alice" in group "system:masters"
  - userARN: arn:aws:iam::000000000000:user/Alice
    username: alice
    groups:
    - system:masters
```

@lukeweber , please double check.

**Comment by lukeweber** [comment]
@ichekrygin - I added the links to source documentation and included an example for each.

**Pull request merged**
