### PR TITLE
Move SQL claims from storage to database namespace

### LINKED ISSUE #300: `storage` resource claims map to `database` resources.
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:** Resource claims and resources appear under consistent, intuitive API hierarchies. For example if SQL database resource claims are under the `storage.crossplane.io` API group, I would expect SQL database resources to be under `storage.provider.crossplane.io`, not `database.provider.crossplane.io`.

**How to reproduce it (minimal and precise):**
Compare the content of the `pkg/apis` tree. For example:

https://github.com/crossplaneio/crossplane/tree/master/pkg/apis/storage
https://github.com/crossplaneio/crossplane/tree/7003069/pkg/apis/gcp/database
https://github.com/crossplaneio/crossplane/tree/7003069/pkg/apis/gcp/storage

Note that blob storage buckets and SQL database resource claims both fall under `storage`, but their resources are separated into the `database` and `storage` classes.

### PR DESCRIPTION
**Pull request by negz**
### Description of your changes

All Crossplane resource claim kinds are in namespaces with managed resource equivalents, for example `kubernetescluster.compute.crossplane.io` maps to managed resource kinds such as `ekscluster.compute.aws.crossplane.io`. The prevalent pattern is that a claim under `${namespace}.crossplane.io` maps to resources under `${namespace}.${provider}.crossplane.io`.

SQL claim types have been the exception to this rule, in that the claim kinds under `storage.crossplane.io` are fulfilled by `database.${provider}.crossplane.io` resource kinds. This commit moves SQL claim kinds to `database.crossplane.io`.

Fixes #300 (my first ever Crossplane issue)

### Checklist

I have:
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Ensured this PR contains a neat, self documenting set of commits.
- [x] Updated any relevant [documentation], [examples], or [release notes].
- [x] Updated the RBAC permissions in [`clusterrole.yaml`] to include any new types.

[documentation]: https://github.com/crossplaneio/crossplane/tree/master/docs
[examples]: https://github.com/crossplaneio/crossplane/tree/master/cluster/examples
[release notes]: https://github.com/crossplaneio/crossplane/tree/master/PendingReleaseNotes.md
[`clusterrole.yaml`]: https://github.com/crossplaneio/crossplane/blob/master/cluster/charts/crossplane/templates/clusterrole.yaml

### CODE REVIEW

**Comment by negz** [comment]
It's probably worth noting there's no new code in this PR. I simply took the existing `pkg/apis/storage`, split its content across `pkg/apis/storage` and `pkg/apis/database`, and renamed `storagev1alpha` imports to `databasev1alpha1` where appropriate.

**Comment by negz** [comment]
> Missed a few example and documentation sites 

@displague  Good catch - fixed.

**Comment by negz** [comment]
As far as I can tell this branch builds and passes all tests - seems like Jenkins has some issues that are causing the build to fail?

**Comment by negz** [comment]
I've snuck in some generated changes to the Copyright years in our license headers. Sonar is configured to require new files refer to the current year, and I have a bad habit of copying and pasting copyright headers from older files. This will ensure I always get the current year (at least until 2020).

**Comment by muvaf** [comment]
I think this PR might have broken master branch. Crossplane pod goes into `CrashLoopBackoff` immediately after deployment with the following logs:
```
2019-07-15T11:17:07.508Z	INFO	crossplane	Sync period	{"duration": "1h0m0s"}
2019-07-15T11:17:07.809Z	INFO	crossplane	Adding schemes
2019-07-15T11:17:07.811Z	INFO	crossplane	Adding controllers
2019-07-15T11:17:07.811Z	INFO	kubebuilder.controller	Starting EventSource	{"controller": "replicationgroup.cache.aws.crossplane.io", "source": "kind source: /, Kind="}
2019-07-15T11:17:07.811Z	INFO	kubebuilder.controller	Starting EventSource	{"controller": "rediscluster.replicationgroup.cache.aws.crossplane.io", "source": "kind source: /, Kind="}
2019-07-15T11:17:07.811Z	INFO	kubebuilder.controller	Starting EventSource	{"controller": "rediscluster.replicationgroup.cache.aws.crossplane.io", "source": "kind source: /, Kind="}
2019-07-15T11:17:07.902Z	INFO	kubebuilder.controller	Starting EventSource	{"controller": "eks.compute.aws.crossplane.io", "source": "kind source: /, Kind="}
2019-07-15T11:17:07.903Z	INFO	kubebuilder.controller	Starting EventSource	{"controller": "kubernetescluster.eks.compute.aws.crossplane.io", "source": "kind source: /, Kind="}
2019-07-15T11:17:07.903Z	INFO	kubebuilder.controller	Starting EventSource	{"controller": "kubernetescluster.eks.compute.aws.crossplane.io", "source": "kind source: /, Kind="}
2019-07-15T11:17:07.906Z	INFO	kubebuilder.controller	Starting EventSource	{"controller": "instance-controller", "source": "kind source: /, Kind="}
2019-07-15T11:17:07.906Z	INFO	kubebuilder.controller	Starting EventSource	{"controller": "instance-controller", "source": "kind source: /, Kind="}
2019-07-15T11:17:07.907Z	INFO	kubebuilder.controller	Starting EventSource	{"controller": "mysqlinstance.rds.aws.crossplane.io", "source": "kind source: /, Kind="}
2019-07-15T11:17:07.907Z	INFO	kubebuilder.controller	Starting EventSource	{"controller": "mysqlinstance.rds.aws.crossplane.io", "source": "kind source: /, Kind="}
2019-07-15T11:17:07.907Z	ERROR	kubebuilder.source	if kind is a CRD, it should be installed before calling Start	{"kind": "MySQLInstance.storage.crossplane.io", "error": "no matches for kind \"MySQLInstance\" in version \"storage.crossplane.io/v1alpha1\""}
github.com/crossplaneio/crossplane/vendor/github.com/go-logr/zapr.(*zapLogger).Error
	/Users/monus/go/src/github.com/crossplaneio/crossplane/vendor/github.com/go-logr/zapr/zapr.go:128
github.com/crossplaneio/crossplane/vendor/sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start
	/Users/monus/go/src/github.com/crossplaneio/crossplane/vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go:89
github.com/crossplaneio/crossplane/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Watch
	/Users/monus/go/src/github.com/crossplaneio/crossplane/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:122
github.com/crossplaneio/crossplane/vendor/github.com/crossplaneio/crossplane/pkg/controller/aws/rds.AddMySQLClaim
	/Users/monus/go/src/github.com/crossplaneio/crossplane/vendor/github.com/crossplaneio/crossplane/pkg/controller/aws/rds/claim.go:122
github.com/crossplaneio/crossplane/vendor/github.com/crossplaneio/crossplane/pkg/controller/aws.AddToManager
	/Users/monus/go/src/github.com/crossplaneio/crossplane/vendor/github.com/crossplaneio/crossplane/pkg/controller/aws/aws.go:49
github.com/crossplaneio/crossplane/vendor/github.com/crossplaneio/crossplane/pkg/controller.AddToManager
	/Users/monus/go/src/github.com/crossplaneio/crossplane/vendor/github.com/crossplaneio/crossplane/pkg/controller/controller.go:44
main.main
	/Users/monus/go/src/github.com/crossplaneio/crossplane/cmd/crossplane/main.go:123
runtime.main
	/usr/local/Cellar/go/1.12.6/libexec/src/runtime/proc.go:200
crossplane: error: Cannot add controllers to manager: cannot watch for storage.crossplane.io/v1alpha1, Kind=MySQLInstance: no matches for kind "MySQLInstance" in version "storage.crossplane.io/v1alpha1"
```

Here is some of my observations:
`kubectl api-resources` returns that entry:
```
mysqlinstances                                 database.crossplane.io         true         MySQLInstance
```
I checked with `kubectl get crd mysqlinstances.database.crossplane.io` and it seems to be the same with the CRD yaml file.

However, if you put a breakpoint on `vendor/k8s.io/apimachinery/pkg/runtime/scheme.go:289`, you'll see that `s.gvkToType` map does not have the MySQLInstance kind at all.

**Comment by displague** [comment]
Looks like https://github.com/crossplaneio/crossplane/blob/master/pkg/apis/apis.go#L37-L50 is missing `database`.

**Comment by muvaf** [comment]
Thanks @displague Also `pkg/apis/database/database.go` seems to import the wrong package. Just raised #581

**Pull request merged**
