### PR TITLE
project setup: add submodule management to Makefile

### PR DESCRIPTION
**Pull request by suskin**
### Description of your changes

Before crossplane can be built locally, the git submodules must be initialized.
Later, a developer may want to update the submodules again by hand. Originally,
this was explained in the documentation, and the command could be copied and
pasted into the terminal. It's more convenient to have a recipe in the Makefile
to do this instead.

Probably the most controversial part of the change will be the change to silently ignore failures of the `include` directives of the Makefile, so I would appreciate any thoughts on that part! I was also not sure what naming people would prefer for the Make targets, so I made some best guesses, but am interested in hearing thoughts on this too.

This isn't related to any existing issue, but came up in the crossplane Slack and the improvement was supported by @negz .

### Checklist

I have:
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Ensured this PR contains a neat, self documenting set of commits.
- [x] Updated any relevant [documentation], [examples], or [release notes].
- [x] Updated the RBAC permissions in [`clusterrole.yaml`] to include any new types.

[documentation]: https://github.com/crossplaneio/crossplane/tree/master/docs
[examples]: https://github.com/crossplaneio/crossplane/tree/master/cluster/examples
[release notes]: https://github.com/crossplaneio/crossplane/tree/master/PendingReleaseNotes.md
[`clusterrole.yaml`]: https://github.com/crossplaneio/crossplane/blob/master/cluster/charts/crossplane/templates/clusterrole.yaml

### CODE REVIEW

**Comment by displague** [comment]
It seems we glance over the initial `git clone` or `go get` command that fetches Crossplane in the first place.  A user may choose to `go get`, `git clone`, `git clone --recursive`, `git clone http://`, `git clone git@`.

It may help to lead off the "Build" section of the docs with our preference so this initial step is not left to chance when a user attempts to reproduce the build.

**Comment by suskin** [comment]
@displague That's a good point; maybe we should consider doing that (in a separate documentation improvement). Since I'm a bit of a noob to `go` projects, I have been assuming that there is an existing idiom which people would use, and that we happen to be using that, and that any of my confusion is part of the ramp-up process.

**Comment by suskin** [comment]
I've made some small changes after some feedback from @bassam and @lukeweber that it'd be nice if the user didn't need to trigger that second `make` invocation. Now, the first invocation of `make` will trigger the second one automatically for the user. Documentation has been updated to match.

**Comment by negz** [comment]
@suskin out of curiosity, how does `make` know to trigger the `fallthrough` target when the includes fail?

**Comment by suskin** [comment]
@negz `make` with no arguments will run the first target in the file, so when the `include` statements fail silently, `fallthrough` is the first target in the file. There's more detail in the [docs for GNU Make](https://www.gnu.org/software/make/manual/html_node/Goals.html). Here's an excerpt, where "goal" means "the thing that will be built":

> By default, the goal is the first target in the makefile (not counting targets that start with a period).

**Pull request merged**
